sonar.projectKey=CoinPusherEngine
sonar.projectName=CoinPusherEngine
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=bin/**,obj/**,.vs/**,.git/**,.github/**
sonar.cs.opencover.reportsPaths=coverage/coverage.opencover.xml
