<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Version>1.0.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\GameEngine\GameEngine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="NeoComboGenerator">
      <HintPath>..\..\Resources\NeoComboGenerator.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Tickets\Tiers\Tier*\tickets.json" />
  </ItemGroup>

</Project>
